add_newline = true
command_timeout = 800
format = """
[  ](fg:#2f2f2f)\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
[└](fg:#b6b6b6)[─](fg:#5c5c5c)[>](fg:#d6bd46) """
right_format = "$time"

[directory]
style = "fg:#f2f2f2 bold"
truncation_length = 2
truncate_to_repo = false
format = "[ $path ]($style)"
home_symbol = "~"

[git_branch]
symbol = ""
style = "fg:#8f8f8f"
format = "[  [$branch]($style)]"

[git_status]
style = "fg:#777777"
format = "[ [$all_status$ahead_behind]($style)]"
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↑${ahead_count}↓${behind_count}"
modified = "~${count}"
staged = "+${count}"
deleted = "-${count}"
renamed = "»${count}"
untracked = "?${count}"
conflicted = "!${count}"
up_to_date = ""

[cmd_duration]
min_time = 1200
style = "fg:#d6bd46"
format = "[  $duration]($style)"

[time]
disabled = false
time_format = "%H:%M"
style = "fg:#5f5f5f"
format = "[$time]($style)"

[nodejs]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[hostname]
disabled = true

[username]
disabled = true
